name: umami账户申请
description: 开放issue来申请一个umami账户
labels: []
body:
  - type: checkboxes
    id: checks
    attributes:
      label: 站点情况检查清单
      description: 请认真检查以下清单中的每一项，并在相符的项前打勾。
      options:
        - required: true
          label: 合法的、非营利性、无商业广告、无木马植入。
        - required: true
          label: 有实质性原创内容的 HTTPS 站点，发布过至少 5 篇原创文章，内容题材不限。
        - required: true
          label: 我保证申请的umami账户仅供我个人使用，且知晓该账户随时可能被收回。
  - type: textarea
    id: config-file
    validations:
      required: true
    attributes:
      label: 站点信息
      description: 请在代码块中填写，不要修改格式。
      value: |
        ```
          name: 站点名字
          link: 站点url
          account: 要申请的umami账户名
          email: 您的邮箱，用于接收umami初始密码
        ```
  - type: markdown
    attributes:
      value: |
        感谢您对本公共umami的信任，我会尽快创建您的账户并邮箱回复您
